// <auto-generated />
namespace test4.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class addCompanyID : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addCompanyID));
        
        string IMigrationMetadata.Id
        {
            get { return "202402010801201_addCompanyID"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
